schema:
  - annict.schema.graphql
  - anilist.schema.graphql
extensions:
  endpoints:
    api.annict.com:
      url: https://api.annict.com/graphql
      headers:
        Authorization: Bearer ${ANNICT_ACCESS_TOKEN}
      introspect: true
    graphql.anilist.co:
      url: https://graphql.anilist.co
      introspect: true
