name: 'Check'

on:
  push:
    branches:
      - 'master'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/yarn-run.yml@master
    permissions:
      contents: 'read'
    with:
      # FIXME: yarn build が壊れているので代替
      script: 'workspace pages build'

  # FIXME: .yarnrc.yml の nodeLinker: pnpm で壊れている
  #  lint:
  #    uses: SlashNephy/.github/.github/workflows/yarn-lint.yml@master
  #    permissions:
  #      contents: 'read'
  #      pull-requests: 'write'

  format:
    uses: SlashNephy/.github/.github/workflows/yarn-format.yml@master
    permissions:
      contents: 'write'
