name: Build Docker Image

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - master

  release:
    types:
      - published

env:
  IMAGE_NAME: ghcr.io/slashnephy/animetl-bot

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare $BRANCH
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Prepare $IMAGE_TAG (on Push to master branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Prepare $IMAGE_TAG (on Push to non-master branch)
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'
        run: echo "IMAGE_TAG=${{ env.BRANCH }}" >> $GITHUB_ENV
      - name: Prepare $IMAGE_TAG (on Release)
        if: github.event_name == 'release'
        run: echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
